// #region Toast Level

/**
 * Visual severity of a toast notification.
 * Maps 1-to-1 to `LogLevel` via the `LEVEL_TO_TOAST` constant in `log.service.ts`.
 */
export type ToastLevel = 'subtle' | 'info' | 'warning' | 'error';
// #endregion Toast Level

// #region Toast Entry

/**
 * A single toast notification managed by {@link ToastStore}.
 */
export interface ToastEntry {
  /** Unique identifier generated by the store on push. */
  readonly id: string;
  /** Translated, user-facing message. */
  readonly message: string;
  /** Visual severity. */
  readonly level: ToastLevel;
  /**
   * Auto-dismiss delay in milliseconds.
   * `0` means the toast is sticky and must be dismissed manually.
   * Default: `5000` for `subtle`/`info`, `0` (sticky) for `warning`/`error`.
   */
  readonly durationMs: number;
}
// #endregion Toast Entry
